services:
  app:
    image: registry.gitlab.com/adrian.ortega/adrianortega.dev:latest
    container_name: adrianortegadev
    restart: unless-stopped
    ports:
      - "5001:8080"
    volumes:
      - content:/app/apps/server/content
      - data:/app/apps/server/data

volumes:
  content:
  data:
